resolver: 'lts-17.2'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- 'vector-0.12.2.0'
- git: https://github.com/fugue/goldplate.git
  commit: 0ac9d399eb7bcac810a1bf4d97ccc08fe6f39f39

nix:
  shell-file: "shell.nix"
