resolver: 'lts-17.2'

# Dev options
ghc-options:
  fregot: -freverse-errors

packages:
- '.'

extra-deps:
- './packages/pcre-simple'
- 'vector-0.12.2.0'
- git: https://github.com/fugue/goldplate.git
  commit: 131b5b12533ae9bff855a442a8d0d28a6a422fdc

nix:
  shell-file: "shell.nix"
